### ISSUE TITLE
About DeepStab Modded dataset

### ISSUE THREAD

**Issue by a1374077658** [btxviny/StabNet#1]
Hello,

Thank you so much for open-sourcing the interesting DeepStab project! I'm trying to run the code following the instructions in the README, but I'm having trouble downloading the DeepStab Modded dataset.

Specifically, when I attempt to access the dataset download link provided in the README, I get the following error:

"Failure, sorry, 1374077658@qq.com cannot be found in the hyu-my.sharepoint.com directory. Please try again later, while we attempt to automatically fix this issue for you."

Could the maintainers please check if this link is valid and accessible, or provide a new download link? I'm really eager to run and learn from this project.

Thank you again for your hard work, and I sincerely look forward to this small issue being resolved soon.

**Comment by btxviny** [comment]
The link was to a modified version of the DeepStab dataset https://arxiv.org/abs/2011.09697, that had undergone deep iterative frame interpolation to generate the steady videos in orderd to minimize perspective mismatch. However, the maintainers removed public access. I changed the link to the original dataset and it should work fine.

**Comment by a1374077658** [comment]
Thank you very much for your patient response.
