### ISSUE TITLE
About training the online model

### ISSUE THREAD

**Issue by a1374077658** [btxviny/StabNet#2]
I recently downloaded your project from GitHub and I'm really impressed with the work you've done. However, I've encountered a few issues during the training process and I was hoping you could help me.

Specifically, I noticed that the online data training stage is missing the PWC_Net and FlowEstimate files from the PWC_src folder, as well as the datagen file. I understand that these might be custom-built components, and I was wondering if you could please provide these files or point me in the right direction to obtain them.

Without these essential components, I'm unable to complete the training process, and I'm eager to explore the full capabilities of your project. I would greatly appreciate if you could share these files or provide guidance on where I can find them.

Thank you in advance for your assistance. I look forward to hearing from you.

**Comment by btxviny** [comment]
I provide a new notebook that uses the pretrained RAFT model, which is available through pytorch's tochvision  to extract the optical flows. It runs slower than PWC_Net but is much easier to use. Just change the directory to the stable videos of the dataset .
https://github.com/btxviny/StabNet/blob/main/Flows_dataset_raft.ipynb

**Comment by a1374077658** [comment]
Thank you very much for your quick response. 
I have an additional question regarding the training data loading process. The ground truth data such as St, St_1, It, Igt, It_1, flow, and features are obtained from the Datagen module, but the project does not provide the code for the Datagen module. Would you please be able to share the Datagen code with me?

**Comment by btxviny** [comment]
Sorry that I missed that. I uploaded a notebook for creating a .txt containing the paths to all dataset inputs, and the datagen.py module. Note that the module uses a generator function that 'yields' the inputs. If you use a more standard pytorch custom generator architecture using __getitem__ https://pytorch.org/tutorials/beginner/basics/data_tutorial.html, it will run much faster, I just haven't had time to change it.

**Comment by a1374077658** [comment]
Thank you again for your excellent work! Your assistance has been invaluable!
